### PR TITLE
photos: Update

### PR DESCRIPTION
**Pull request by georgebisbas**

### CODE REVIEW

**Comment by georgebisbas** [comment]
@AntonLydike could you help with this?

**Comment by AntonLydike** [comment]
Ah sorry, yes! I'll see if I can build locally and check it out!

**Comment by AntonLydike** [comment]
image



We need to get these into the proper aspect ration, and then we can merge I think!

**Comment by tobiasgrosser** [comment]
I had to fix the aspect ratio of Paul's picture, otherwise this looks great.

**Pull request merged**
